name: Tests

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
      tag:
        type: string
        description: tag to deploy
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print env argument
        run: | 
          echo User selected environment ${{ inputs.environment }}
          echo User selected tag ${{ inputs.tag }}
