name: Create RC
on:
  workflow_dispatch:
jobs:
  cut_release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Cut new tag
        run: |
          echo "TODO: Create a new tag"
          git describe --abbrev=0 > temp.txt
          NEW_TAG=awk -F. '/[0-9]+\./{$2++;print}' OFS=. temp.txt
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create ${{ env.NEW_TAG }} \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ env.NEW_TAG }}" \
              --generate-notes 
    outputs:
      newTag: ${{ env.NEW_TAG }}
  deploy:
    needs: cut_release
    uses: ./.github/workflows/deploy.yml
    with:
      tag: ${{ needs.cut_release.outputs.newTag }}
      environment: qa
