name: Create RC
on:
  workflow_dispatch:
jobs:
  cut_release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Cut new tag
        run: |
          echo "TODO: Create a new tag"
          echo "NEW_TAG=1.0.0" >> $GITHUB_ENV
      - name: Deploy to QA
        uses: ./.github/workflows/deploy.yml
        with:
          tag: ${{ env.NEW_TAG }}
          environment: qa
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create ${{ inputs.tag }} \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ inputs.tag }}" \
              --generate-notes    
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      tag: ${{ env.NEW_TAG }}
      environment: qa
