name: Create RC
on:
  workflow_dispatch:
jobs:
  cut_release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Cut new tag
        run: |
          
