name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
          - prod
jobs:
  print-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print env argument
        run: echo ${{ inputs.environment }}           
