name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
          - prod
jobs:
  print-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print env argument
        run: echo User selected environment ${{ inputs.environment }}           
  deploy-dev:
    permissions: write-all
    if: ${{ inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: echo "Deploying to dev"
      
      - uses: actions/checkout@v1
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment-dev
        with:
          token: '${{ github.token }}'
          environment: production
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: http://michaeldpeterson.net
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}          
  deploy-qa:
    if: ${{ inputs.environment == 'qa' }}
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: deploy
        run: echo "Deploying to qa"
  deploy-prod:
    if: ${{ inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo "Deploying to prod"        
